# Generated by Django 3.2.7 on 2022-01-08 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydiaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordTime', models.CharField(max_length=5)),
                ('recordDate', models.DateTimeField()),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydiaryapp.patient')),
                ('resourceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydiaryapp.resource')),
            ],
        ),
    ]
