# Generated by Django 3.2.7 on 2022-01-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiaryapp', '0003_schedulerecord_recordtimeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='lpuName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
