# Generated by Django 3.2.7 on 2022-01-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiaryapp', '0004_resource_lpuname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='shortName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
