# Generated by Django 3.2.7 on 2022-01-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiaryapp', '0005_patient_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='maskUnavail_add',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='timeUnavail_add',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
