# Generated by Django 3.2.7 on 2022-01-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiaryapp', '0006_auto_20220112_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='maskUnavail',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='maskUnavail_add',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='timeUnavail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='timeUnavail_add',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
