name: DJANGO DEPLOY

on:
  workflow_dispatch:


jobs:
  deployDJ:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: django via rsync deploy
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: mydiary
          remote_path: www/django
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
