name: DJANGO DEPLOY

on:
  push:
    branches:
      - master


jobs:
  deployDJ:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: django via rsync deploy
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: mydiary
          remote_path: www/django
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
      - name: connect to EC2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.KEY }}
           port: ${{ secrets.PORT }}
           script: |
                  cd www/django/mydiary
                  sudo docker stop mydiary
                  sudo docker container rm -f mydiary
                  sudo docker build -t mydiary .
                  sudo docker run -d -p 8000:8000 --name="mydiary" mydiary

