name: DJANGO DEPLOY

on:
  workflow_dispatch:


jobs:
  deployDJ:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: django via rsync deploy
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: mydiary
          remote_path: www/django
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
  dockerB:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: connect to EC2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: appleboy/ssh-action@master
        width:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.KEY }}
           port: ${{ secrets.PORT }}
           script: |
                  cd www/django/mydiary
                  sudo docker build - t mydiary .

